name: commitlint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install commitlint
        run: |
          npm install commitlint@19.4.0
          npm i -D @commitlint/config-conventional

          echo "export default {
            extends: ['@commitlint/config-conventional'],
            rules: {
              'body-max-line-length': [2, 'always', Infinity],
            },
          };" > commitlint.config.ts

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
