name: Frontend

on:
  pull_request:
    paths:
      - "frontend/**"
  push:
    paths:
      - "frontend/**"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        working-directory: frontend
        run: npm ci
      - name: "[ESLint] Run code linter"
        working-directory: frontend
        run: npm run eslint:lint
      - name: "[Prettier] Run code linter"
        working-directory: frontend
        run: npm run prettier:lint
      - name: Build
        working-directory: frontend
        run: npm run build