name: ShellCheck

on:
  push:
    paths:
      - '**/.sh'
    branches:
      - "main"
  pull_request:
    paths:
      - '**/.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: redhat-plumbers-in-action/differential-shellcheck@v5.4.0
